### PR TITLE
Acta rename

### LINKED ISSUE #15: Acta Catalyst name
@sadrasabouri 
Change the name of **acta catalyst** to  **Pd decorated Ni–Co/rGO** everywhere in dataset

@sarminh 
Consider this issue for datapaper

### PR DESCRIPTION
**Pull request by sadrasabouri**
#### Reference Issues/PRs
close #15 
#### What does this implement/fix? Explain your changes.
<b>Acta</b> renamed to <b>Pd decorated Ni–Co/rGO Catalyst</b>.
@kasraaskari 
There might be some mistakes in `Pd decorated Ni–Co_rGO Catalyst/`, I've changed <b>Acta ...TM</b> to <b>Pd decorated Ni–Co/rGO ...</b> but I'm not sure about it.

### CODE REVIEW

**Comment by sadrasabouri** [comment]
@sepandhaghighi `test.py` is working OK for me, although CI AppVeyor build failed.
 It seems `os.path.join` adds two extra `/`s.

**Comment by sepandhaghighi** [comment]
> @sepandhaghighi `test.py` is working OK for me, although CI AppVeyor build failed.
> It seems `os.path.join` adds two extra `/`s.

It's because of character between `Ni` and `Co` is not a standard dash!!!!
Use this for file and folder names  : `Pd-Decorated-Ni-Co-rGO Catalyst`

**Review by sepandhaghighi — CHANGES_REQUESTED** [review]
@sadrasabouri Thanks for your efforts ;-)
Please follow the other sections naming pattern, for example you should use `Decorated` instead of `decorated` in **some places** (folder name, notebook name and ...)

**Review by sepandhaghighi — APPROVED** [review]
@sadrasabouri LGTM, thanks for your effort ;-)
@kasraaskari I'm not sure about this : `Acta AnodeTM` -- > `Pd Decorated Ni–Co/rGO`
Is it true?

**Review by kasraaskari — APPROVED** [review]

**Review by kasraaskari — APPROVED** [review]

**Pull request merged**
